### ISSUE TITLE
Doors don't work

### ISSUE THREAD

**Issue by hsanger** [SurvivReloaded/survivreloaded-server#17]
Doors haven't been implemented yet.

**Comment by JoeSquared777** [comment]
I don't know how else to comment (talk) to you directly, but Hello! I've been trying to get on to this project through the fandom, but it was blocked. I don't know much coding (in terms of typing anyways), but I can pick up on stuff pretty fast, and can do whatever you need me to do. (As long as it's reasonable.) 

P.S. If there are any sites to learn TypeScript/Javascript, what would you recommend? Also I have node.js downloaded so theres that.

**Comment by lopste** [comment]
> I don't know how else to comment (talk) to you directly, but Hello! I've been trying to get on to this project through the fandom, but it was blocked. I don't know much coding (in terms of typing anyways), but I can pick up on stuff pretty fast, and can do whatever you need me to do. (As long as it's reasonable.)
> 
> P.S. If there are any sites to learn TypeScript/Javascript, what would you recommend? Also I have node.js downloaded so theres that.
https://www.javascript.com/ looks good for learning JavaScript, but for TypeScript there’s an official one: https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html I don’t know any others, but a general tip for everything programming: Google is your friend.

**Comment by JoeSquared777** [comment]
> > I don't know how else to comment (talk) to you directly, but Hello! I've been trying to get on to this project through the fandom, but it was blocked. I don't know much coding (in terms of typing anyways), but I can pick up on stuff pretty fast, and can do whatever you need me to do. (As long as it's reasonable.)
> > P.S. If there are any sites to learn TypeScript/Javascript, what would you recommend? Also I have node.js downloaded so theres that.
> 
> https://www.javascript.com/ looks good for learning JavaScript, but for TypeScript there’s an official one: https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html I don’t know any others, but a general tip for everything programming: Google is your friend.

I looked at it, but when I compare it to this code in the game, it's completely different functions. Could you take an example of the code and label how it works or something? Thanks.

**Comment by Saksham-Leaf** [comment]
> > > I don't know how else to comment (talk) to you directly, but Hello! I've been trying to get on to this project through the fandom, but it was blocked. I don't know much coding (in terms of typing anyways), but I can pick up on stuff pretty fast, and can do whatever you need me to do. (As long as it's reasonable.)
> > > P.S. If there are any sites to learn TypeScript/Javascript, what would you recommend? Also I have node.js downloaded so theres that.
> > 
> > 
> > https://www.javascript.com/ looks good for learning JavaScript, but for TypeScript there’s an official one: https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html I don’t know any others, but a general tip for everything programming: Google is your friend.
> 
> I looked at it, but when I compare it to this code in the game, it's completely different functions. Could you take an example of the code and label how it works or something? Thanks.

Can you elaborate?
