### ISSUE TITLE
New issue with the updates

### ISSUE THREAD

**Issue by Viswas-Programs** [SurvivReloaded/survivreloaded-server#24]
![image](https://user-images.githubusercontent.com/115633223/224617674-fd45fe6f-2271-4f01-b6bf-f6ecf923914c.png)
This is what happens when I run npm start, It build successfully, but, npm start doesn't work anymore!
I might be annoying, so sorry about that.

**Comment by lopste** [comment]
It looks like it was in the `.gitignore`, and I saw that @hsanger fixed it. If you pull from the repository again, it should work!

**Comment by Viswas-Programs** [comment]
Yeah IK about that, I forgot to close this question.
I pulled in the latest commits, and it did work, after that, works
