### ISSUE TITLE
Website really slow than before

### ISSUE THREAD

**Issue by Viswas-Programs** [SurvivReloaded/survivreloaded-server#27]
I left a complaint here saying that the game server had lags, now it takes 2 minutes just to load up the site, and it's still not finished loading yet!
Before the recent update in the past week, the website launched fine and fast, really fast than surviv.io itself, it was just the gameplay that sometimes lagged.
Now, I've been waiting for 5 minutes (real) and it's still stuck loading the notification permission screen!
Now, it takes 3 minutes fully to load up the background of the website.

**Comment by hsanger** [comment]
It might be your Internet. Have other sites gotten slower, or is it just survivreloaded.com?

**Comment by hsanger** [comment]
Try [https://test.survivreloaded.com](https://test.survivreloaded.com). If it also takes a while to load, it's most likely your Internet. If not, it may be an issue with the new update.

**Comment by Viswas-Programs** [comment]
Oh, sorry for late reply (timezone!)
And other website loads fast, only survivreloaded.com is slow, and test.survivreloaded.com acts in the same way
It's also really slow, (2 minutes waiting, still a white background indicating that it's still loading!)

**Comment by Viswas-Programs** [comment]
Following up, test.survivreloaded.com works and loads fast, just like before
but the main survivreloaded.com website still doesn't load up!

**Comment by hsanger** [comment]
I set up Cloudflare for the website. It should be much faster now.
