### ISSUE TITLE
I fixed the bullet speed issue

### ISSUE THREAD

**Issue by sentry456123** [SurvivReloaded/survivreloaded-server#46]
In src/game/bullet.ts line 91

I replaced this code
this.body.setLinearVelocity(direction.clone().mul(bulletData.speedMultiplier ?? 1));

with
this.body.setLinearVelocity(direction.clone().mul(bulletData.speed / 1000.0));

So now the server can calculate the speed of every type of bullet perfectly.

Hope this helps!

**Comment by hsanger** [comment]
This is what we ended up doing. Thanks for your help!
