### ISSUE TITLE
Map Misgeneration or Bad Generation 

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [SurvivReloaded/survivreloaded-server#5]
# Random Area Generation without Information of the Area
![](https://i.imgur.com/WcYCQxc.png)
![](https://i.imgur.com/IyTLvCC.png)

# Poor Generation 
![](https://i.imgur.com/HzROp1E.png)
![](https://i.imgur.com/31zWVC3.png)
![](https://i.imgur.com/IX19XwJ.png)
![](https://i.imgur.com/8ei4Xps.png)
![](https://i.imgur.com/CTkndLv.png)
![](https://i.imgur.com/Dmeg6Jr.png)
![](https://i.imgur.com/inLGoxd.png)
![](https://i.imgur.com/qPKnHlh.png)

# Poor Area Generation with Random Freezes
![](https://i.imgur.com/oSfEIRK.png)
![](https://i.imgur.com/zhTGQQN.png)
![](https://i.imgur.com/8xl1VUl.png)
![](https://i.imgur.com/hFMtiJR.png)
![](https://i.imgur.com/60jSjJt.png)
![](https://i.imgur.com/dUmUJa7.png)

# No Game Load / Generation Status
![](https://i.imgur.com/yYFPhiA.png)

**Comment by hsanger** [comment]
Very detailed report, thank you!

**Comment by hsanger** [comment]
All obstacle generation issues have been fixed!
