### ISSUE TITLE
I hate this game very much

### ISSUE THREAD

**Issue by darik9pl** [SurvivReloaded/survivreloaded-server#66]
Reasons why i hate this game?

1. Stupid 2 years olds shoot me on the game for no reason.
2. And they are laughing about it even it's not funny!

My brother told me to not play that copy of surviv.io.

Can you add the Report system?

**Comment by leo78913** [comment]
skill issue

**Comment by darik9pl** [comment]
> skill issue

no

**Comment by leo78913** [comment]
yes
