### ISSUE TITLE
How Do I Run This With Github Codespaces

### ISSUE THREAD

**Issue by EagleEye2010** [SurvivReloaded/survivreloaded-server#70]
It's self explanatory. Any help would be appreciated. Thanks!

**Comment by lmssiehdev** [comment]
what problem are you having exactly?

**Comment by EagleEye2010** [comment]
Also it returns an error when I run any of these commands

**Comment by hsanger** [comment]
What's the error?

**Comment by EagleEye2010** [comment]
Here is an image of it not working. It returns the same thing for  `npm run build` and `npm run dev`

**Comment by EagleEye2010** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/120738530/231811754-f06785f8-11e7-494d-a786-a1deef972a7a.png">

**Comment by hsanger** [comment]
Are you sure you cloned the repo correctly? The following sequence of commands should work:
```
git clone https://github.com/SurvivReloaded/survivreloaded-server
cd survivreloaded-server
git clone https://github.com/SurvivReloaded/survivreloaded-client public
npm install
npm run build
npm run dev
```

**Comment by EagleEye2010** [comment]
Oh did not realize I had to do `cd survivreloaded-server`. That seems to do the trick. Thanks!
