### ISSUE TITLE
Github Codespaces Returns "Failed Joining Game"

### ISSUE THREAD

**Issue by EagleEye2010** [SurvivReloaded/survivreloaded-server#74]
Github Codespaces runs the client, but returns "Failed Joining Game", even when I have 3 players all joining at the same time. I don't know if this is Github Codespaces acting up or if there is some JSON value I have to tweak, but it ain't working. Go to [https://eagleeye2010-sturdy-train-699q555vgr7h546r-8000.preview.app.github.dev/](https://eagleeye2010-sturdy-train-699q555vgr7h546r-8000.preview.app.github.dev/) to see for yourself. I think it has to do with the website URL, but I don't know for certain, and even if I did, I wouldn't know how to fix it. All help would be appreciated. I apologize if this is wasting your time. Thanks.

**Comment by hsanger** [comment]
Try adding this line to `config.json`:
```json
"webSocketAddr": "eagleeye2010-sturdy-train-699q555vgr7h546r-8000.preview.app.github.dev:8001",
```

**Comment by EagleEye2010** [comment]
I'll try that.

**Comment by hsanger** [comment]
Hang on, it's actually `webSocketAddress`, not `webSocketAddr`:
```json
"webSocketAddress": "eagleeye2010-sturdy-train-699q555vgr7h546r-8000.preview.app.github.dev:8001",
```

**Comment by EagleEye2010** [comment]
That does not seem to work either. I did notice that `"https": false` might have been a root of issues. Also 8000 returns client but port 8001 return error 502: bad gateway

**Comment by hsanger** [comment]
Yeah, setting `https` to `true` might fix it. Is `webSocketPort` set to `8001`?

**Comment by EagleEye2010** [comment]
Setting https to true returns another error:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/120738530/231889385-46b9d299-789b-471b-86de-a0657aac5935.png">
Also websocketport is set to 8001

**Comment by hsanger** [comment]
I noticed the port number appears in the URL. This might fix it:
```
"webSocketAddress": "eagleeye2010-sturdy-train-699q555vgr7h546r-8001.preview.app.github.dev:8001",
```

**Comment by EagleEye2010** [comment]
It still crashes:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/120738530/231896863-41f0cc36-c4df-4daa-aec5-24b8b0ad592e.png">

**Comment by lmssiehdev** [comment]
@EagleEye2010 join the discord https://discord.resurviv.io, it's easier to communicate that way.

**Comment by EagleEye2010** [comment]
I don't do discord, sorry. I'll just download the file and run it from my computer the old fashioned way.

**Comment by lmssiehdev** [comment]
![image](https://user-images.githubusercontent.com/122186255/231902203-942b1219-21da-460f-a8a2-087d86ddb710.png)

had to switch the WebSocket server from private to public for it to work.

![image](https://user-images.githubusercontent.com/122186255/231902283-88db6b24-b22c-4fec-aa44-0debd6024b53.png)
